repo_url: https://github.com/xenondevs/Docs
repo_name: xenondevs/Docs
copyright: Copyright &copy; 2026 xenondevs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xenondevs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/EpVMXtXB2t

theme:
  name: material
  logo: assets/logo.png
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables
  - def_list
  - footnotes

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
